name: ecommerce_admin_panel
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  # Utility Package
  url_launcher: ^6.3.2
  intl: ^0.20.2
  lottie: ^3.3.2
  clipboard: ^3.0.13
  image_picker: ^1.2.1
  flutter_dropzone: ^4.2.1
  flutter_typeahead: ^5.2.0
  connectivity_plus: ^7.0.0
  multi_select_flutter: ^4.1.3
  cached_network_image: ^3.4.1
  flutter_native_splash: ^2.4.7
  smooth_page_indicator: ^2.0.1
  logger: ^2.6.2
  shimmer: ^3.0.0

  # Web Specific
  web: ^1.1.1
  http: ^1.6.0
  fl_chart: ^1.1.1
  data_table_2: ^2.7.2
  url_strategy: ^0.3.0

  # State Management
  get_x: ^5.0.0
  get_storage: ^2.1.1

  # Firebase
  firebase_storage: ^13.0.4
  firebase_auth: ^6.1.3
  cloud_firestore: ^6.1.1
  firebase_core: ^4.3.0

  # Icons
  cupertino_icons: ^1.0.8
  iconsax: ^0.0.8



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true


  #------------Local Assets-----------#
  assets:
    - assets/logos/
    - assets/images/content/
    - assets/images/animations/
    - assets/icons/payment_methods/
  
  #------------Local Fonts------------#
  fonts:
    - family: Urbanist
      fonts:
        - asset: assets/fonts/urbanist/Urbanist-Light.ttf
          weight: 300
        - asset: assets/fonts/urbanist/Urbanist-Regular.ttf
          weight: 400
        - asset: assets/fonts/urbanist/Urbanist-Italic.ttf
          style: italic
        - asset: assets/fonts/urbanist/Urbanist-Medium.ttf
          weight: 500
        - asset: assets/fonts/urbanist/Urbanist-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/urbanist/Urbanist-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/urbanist/Urbanist-Bold.ttf
          weight: 800
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
